### PR TITLE
Update `master` to v9.51.0

### PR DESCRIPTION
**Pull request by adamkrellenstein**
Potential problem points:
* <s>Requires upgrade to CLI v1.1.0 (to be released simultaneously)</s>
* Mandatory upgrade by block 352000, or around 2015-04-14.

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
@btcdrak, @robby-dermody, can you take a look at this?

I think it's pretty near ready.

**Comment by adamkrellenstein** [comment]
Also, @mtbitcoin, @deweller, @snitko.

**Comment by deweller** [comment]
The API change that removes `get_asset_info(assets)` will definitely break some integrations with counterpartyd (including ours).  A prominent warning and brief explanation of the replacement API call would be much appreciated by us app developers.

**Comment by adamkrellenstein** [comment]
@ouziel-slama, are you okay with leaving all of those API calls in for now and just officially deprecating them? I don't like the idea of combining a mandatory upgrade with a compatibility break in the API.

**Comment by robby-dermody** [comment]
+1 to not removing the API calls, and deprecating them for now

**Comment by ouziel-slama** [comment]
done: https://github.com/CounterpartyXCP/counterpartyd/commit/5ed578321d843bedfbc985def714a7d2b9930854

**Comment by robby-dermody** [comment]
ACK from me. Been running this with counterblock 1.2.0 and besides the counterparty-cli version issue, things seem to be working well.

**Comment by adamkrellenstein** [comment]
The CLI version issue has been solved: https://github.com/CounterpartyXCP/counterpartyd/commit/3897fd3a697e8eae05bdf6a87e8330042b21784f

You can now run v9.51.0 with current version of the CLI.

**Pull request merged**
