### PR TITLE
Distinguish between explorer and wallet dependencies; separate CLI from library

### PR DESCRIPTION
**Pull request by ouziel-slama**
`counterpartyd.py` is split into two components:

counterparty-server.py

- `counterparty-server` have only one dependency: a blockchain explorer (`BACKEND_* in the `config.py`)
- `counteparty-server.py` manages now only these actions: `server`, `reparse`, `rollback` and `kickstart`
- BACKEND_RPC_* are replaced by BACKEND_*
- removed support of parameters `bitcoind_rpc_*` in the configuration file
- `BLOCKCHAIN_SERVICE_NAME` is replaced by `BACKEND_NAME`
- `jmcorgan` is replaced by `addrindex` (temporarily `jmcorgan` is still accepted)
- support of Insight, Blockr and SoChain are removed. Only `jmcorgan` backend is supported for now, but a wrapper for another wallet can be easily added in the `lib/backend` folder.

counterparty-client.py

- `counterparty-client` have two dependencies: a `counterparty-server` and a wallet.
- it is completly independent of the `lib` folder.
- It have its own configuration file (~/.config/counterparty-client/counterparty-client.conf) and don't uses a database
- Only Bitcoin Core wallet is supported for now, but a wrapper for another wallet can be easily added in the `client/wallet` folder.

other modifications:

- `requests` library is always used to make RPC calls

The final goal of this PR is to use a different repository for `counterparty-client.py`. That is why there is some duplicate code in `lib` and `client` folders:

- `util_windows.py` and `script.py` are duplicated.
- `client/util.py` contains some functions of `lib/util.py` but it never uses the database but RPC calls instead.

API changes

- added methods: `get_holders(asset)`, `search_pubkey(pubkeyhash, provided_pubkeys=None)`
- removed method: `get_wallet()`
- parameter `privkey` of the method `sign_transaction()` is now mandatory.

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
Solves #588.
Solves #572.

**Comment by ouziel-slama** [comment]
UPDATE:

- `counterparty-client.py` and `counterpary-server.py` were moved here: https://github.com/CounterpartyXCP/counterparty-cli.git
There is some works before I can promote the `develop` branch to `master` (mainly the README and setup.py)

- `countepartyd` it's now a Python package library, and can be installed via `pip`. See the updated README.

**Comment by adamkrellenstein** [comment]
@ouziel-slama, is this ready to merge?

**Comment by adamkrellenstein** [comment]
It looks good to me.

**Comment by adamkrellenstein** [comment]
The ChangeLog needs to say the the CLI is being moved out of this repository.

**Pull request merged**
