### PR TITLE
Setup for CircleCI

### PR DESCRIPTION
**Pull request by gotcha**
CircleCI is a very good service
Among other things, quicker than TravisCI

### CODE REVIEW

**Comment by gotcha** [comment]
This would imply that one member of CounterpartyXCP organization makes a free account at https://circleci.com/ with GH account

**Comment by adamkrellenstein** [comment]
I'm willing to try this out. (Speed might be an issue in the near future, if we're going to be doing full DB reparses: https://github.com/CounterpartyXCP/counterpartyd/issues/642)

@gotcha: can you squash this down to one commit, and change it to use Python 3 (https://circleci.com/gh/CounterpartyXCP/counterpartyd/1)?

**Comment by gotcha** [comment]
@adamkrellenstein There is no way of testing 3 by itself. But they can run tests for multiple versions.
I guess you want 3.2 and 3.3 as well. But not 3.1 ?

**Comment by adamkrellenstein** [comment]
@gotcha, not 2.7? I think Python 3.2, 3.3 and 3.4 would be good.

**Comment by gotcha** [comment]
@adamkrellenstein 
- Why 2.7 ? counterpartyd README explicitly defines Python 3 as a dependency. Is that wrong ?
- I thought CircleCI was able to test multiple versions of Python but it seems I was wrong. Nevertheless, you only test 3.4 on Travis

**Comment by gotcha** [comment]
@adamkrellenstein squashed to one commit

**Comment by adamkrellenstein** [comment]
@gotcha, right now CircleCI is running 2.7, and it's failing... It should be 3.4, say.

**Comment by gotcha** [comment]
@adamkrellenstein I am not sure I understand what you mean. Did you setup on CircleCI ? If yes and build fails, I guess there is an issue with master/develop branch.

I have setup circleCI for counterpartyd develop branch in a copy with my account and it does work:

https://circleci.com/gh/gotcha/testcounter

**Comment by adamkrellenstein** [comment]
Ah, my bad. I was running it without your `circle.yml`, so it was defaulting to Python 2.

Thanks for the PR!

**Pull request merged**
