### PR TITLE
Default to Using `OP_RETURN` Encoding When Possible

### PR DESCRIPTION
**Pull request by adamkrellenstein**
80-byte `OP_RETURN` support is coming as well: #690

### CODE REVIEW

**Comment by btcdrak** [comment]
ACK ACK ACK

**Comment by btcdrak** [comment]
You also need to make a change in clearwallet to use auto encoding.

https://github.com/ClearingHouse/clearwallet/commit/2327c79eed32f10b756408663b26cd56d646a30b

Which also relies on this which we got merged into Bitcore

**Comment by btcdrak** [comment]
You also need to make a change in clearwallet to use auto encoding.

https://github.com/ClearingHouse/clearwallet/commit/2327c79eed32f10b756408663b26cd56d646a30b

Which also relies on this which we got merged into Bitcore https://github.com/bitpay/bitcore/commit/0977a2c23b7ad4f20467aa70237d097b0b41eb05

And this https://github.com/ClearingHouse/clearwallet/commit/0d0b4b925a48a34fe7265929a6909bd7d1e092e5

**Comment by adamkrellenstein** [comment]
@btcdrak: counterwallet issue created (https://github.com/CounterpartyXCP/counterwallet/issues/688)

**Pull request merged**
