### PR TITLE
[#752] Optimize and make optional asset conservation checking

### PR DESCRIPTION
**Pull request by ouziel-slama**
In my configuration, with the new method, `check.asset_conservation()` takes less than 2s instead more than 155s.

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
Awesome

**Comment by deweller** [comment]
woo hoo!

**Comment by mtbitcoin** [comment]
woot !

**Comment by mtbitcoin** [comment]
Can you clarify on the "make optional asset conservation checking" ?? 

What is the conservation checking for ?

**Comment by adamkrellenstein** [comment]
@mtbitcoin, it's a sanity check to make sure that the number of assets in balances and in escrow sum to the total number issued. If there were ever a mistake in the protocol that deleted on created an asset unintentionally, clients running the conservation check would halt with an error.

**Comment by mtbitcoin** [comment]
ok. Noted.

As a tradeoff, have you considered just running the sanity checks say after XX number of block (once a day, etc) ?

side note: I have found that with the conservation checks off, the mempool transactions shows up really quick and works well for checking the pending transactions. I've always had this issue (which wasn't an issue in ealier on).  So in hindsight, it looks like the issue might have been due to the sanity check and increase volume of assets registered instead

**Comment by adamkrellenstein** [comment]
There's no best option. The optimal setting depends on the particular use case. Feel free to patch the code to run it only every, say, 100 blocks. I think the likelihood of the sanity check catching an error is pretty low.

**Pull request merged**
