### PR TITLE
[#707] Fix Dividend Fee Check

### PR DESCRIPTION
**Pull request by ouziel-slama**

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
Should this be a protocol change, or does this patch *only* avoid the triggering of a fatal exception?

**Comment by ouziel-slama** [comment]
hum... good question. I would say the latter, but not 100% sure.. What do you think?

**Comment by adamkrellenstein** [comment]
We need to be 100% sure to merge it now. :-/ If we can't be, then we should just include this in v9.50.0.

**Comment by ouziel-slama** [comment]
hum.. If the case occurs, no transactions will be recorded for the block and following blocks, all `counterparty-server` instances will just crash. So we can not say that is really a protocol change. If you agree with this reasoning so yes I think we can merge now and cherry-pick to master.

**Comment by adamkrellenstein** [comment]
I looked it over carefully, and I think that indeed if and only if this condition is satisfied with the current version, `util.debit()` will throw an uncaught exception. However, I think we should have full test coverage here before this gets merged in.

**Comment by ouziel-slama** [comment]
I added a test for this edge case, and seems there is already a test for all existing errors in `vectors.py`. @Millz0r, can you please confirm we have a test for every kind of error in`dividend.py` ?

**Comment by ouziel-slama** [comment]
OK, I just add test for the last untested case in `dividend.validate().
In `dividend.py` only this case is no tested: https://github.com/CounterpartyXCP/counterpartyd/blob/develop/counterpartylib/lib/messages/dividend.py#L159
AND old protocol. It's a general issue, the test suite only test the last version of the protocol, so this kind of block is never tested: https://github.com/CounterpartyXCP/counterpartyd/blob/develop/counterpartylib/lib/messages/dividend.py#L85

**Comment by Millz0r** [comment]
As far as I can tell there are five unit tests still not covered:
- old protocol mentioned above
- two cases of BTC send in compose and parse
- invalid struct in parse
- one unpack case in parse where len(message) == LENGTH_1 . I'm not sure if this would be affected? https://github.com/CounterpartyXCP/counterpartyd/blob/707/counterpartylib/lib/messages/dividend.py#L152

Besides that I think we are covered well enough.

**Comment by adamkrellenstein** [comment]
None of that's relevant except for the test of the old protocol, which is difficult. :/ (#369)

**Comment by adamkrellenstein** [comment]
@ouziel-slama, can you do the cherry-pick?

**Comment by ouziel-slama** [comment]
@adamkrellenstein, just did a PR on master. I will merge as soon tests will finish on circle.

**Pull request merged**
